app/config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('education.urls')),
]

app/education/urls.py
from django.conf.urls import url

from education.views import school_list, student_list, school_detail, student_detail

urlpatterns = [
    url(r'^school/$', school_list),
    url(r'^school/(\d)/$', school_detail),
    url(r'^student/$', student_list),
    url(r'^student/(\d)/$', student_detail),
]

app/education/models.py
from django.utils import timezone

from django.db import models


class School(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

app/education/views.py
from django.http import HttpResponse
from django.shortcuts import render

from education.models import School, Student


def school_list(request):
    schools = School.objects.all()

    context = {
        'schools': schools,
    }

    return render(request, 'school_list.html', context)


def school_detail(request, school_id):
    school = School.objects.get(id=school_id)
    context = {
        'school': school,
    }
    return render(request, 'school_detail.html', context)


def student_list(request):
    students = Student.objects.all()

    context = {
        'students': students
    }

    return render(request, 'student_list.html', context)


def student_detail(request, student_id):
    student = Student.objects.get(id=student_id)
    context = {
        'student': student
    }
    return render(request, 'student_detail.html', context)

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Education</title>
</head>
<body>
    {% block context %}

    {% endblock %}
</body>
</html>

app/templates/school_detail.html
{% extends 'base.html' %}
{% block context %}
        <p>{{ school.name }}</p>
        <p>{{ school.description}}</p>
        <p>
            재학생 명단 :<br><br>
            {% for student in school.student_set.all %}
            {{ student }}
        </p>
    {% endfor %}
{% endblock %}

app/templates/school_list.html
{% extends 'base.html' %}
{% block context %}
    {% for school in schools %}
        <p>{{ school.name }}</p>
    {% endfor %}
{% endblock %}

app/templates/student_detail.html
{% extends 'base.html' %}
{% block context %}
    <p>{{ student.name }}</p>
    <p>{{ student.school }}</p>
    <p>{{ student.created_at }}</p>
{% endblock %}

app/templates/student_list.html
{% extends 'base.html' %}
{% block context %}
    {% for student in students %}
        <p>{{ student.name }}</p>
    {% endfor %}
{% endblock %}